/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * An artifact
 */
@ApiModel(description = "An artifact")

public class Artifact {
  public static final String JSON_PROPERTY_PATH = "path";
  @JsonProperty(JSON_PROPERTY_PATH)
  private String path;

  public static final String JSON_PROPERTY_NODE_INDEX = "node_index";
  @JsonProperty(JSON_PROPERTY_NODE_INDEX)
  private Long nodeIndex;

  public static final String JSON_PROPERTY_URL = "url";
  @JsonProperty(JSON_PROPERTY_URL)
  private String url;

  public Artifact path(String path) {
    this.path = path;
    return this;
  }

   /**
   * The artifact path.
   * @return path
  **/
  @ApiModelProperty(required = true, value = "The artifact path.")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public Artifact nodeIndex(Long nodeIndex) {
    this.nodeIndex = nodeIndex;
    return this;
  }

   /**
   * The index of the node that stored the artifact.
   * minimum: 0
   * @return nodeIndex
  **/
  @ApiModelProperty(required = true, value = "The index of the node that stored the artifact.")
  public Long getNodeIndex() {
    return nodeIndex;
  }

  public void setNodeIndex(Long nodeIndex) {
    this.nodeIndex = nodeIndex;
  }

  public Artifact url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL to download the artifact contents.
   * @return url
  **/
  @ApiModelProperty(required = true, value = "The URL to download the artifact contents.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Artifact artifact = (Artifact) o;
    return Objects.equals(this.path, artifact.path) &&
        Objects.equals(this.nodeIndex, artifact.nodeIndex) &&
        Objects.equals(this.url, artifact.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, nodeIndex, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Artifact {\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    nodeIndex: ").append(toIndentedString(nodeIndex)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

