/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md). API V1 [remains accessible here](https://circleci.com/docs/api/v1/)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * ContextOwner
 */

public class ContextOwner {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private UUID id;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @JsonProperty(JSON_PROPERTY_SLUG)
  private String slug;

  /**
   * The type of the owner. Defaults to \&quot;organization\&quot;. Accounts are only used as context owners in server.
   */
  public enum TypeEnum {
    ACCOUNT("account"),
    
    ORGANIZATION("organization");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @JsonProperty(JSON_PROPERTY_TYPE)
  private TypeEnum type;

  public ContextOwner id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * The unique ID of the owner of the context. Specify either this or slug.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique ID of the owner of the context. Specify either this or slug.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ContextOwner slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * A string that represents an organization. Specify either this or id. Cannot be used for accounts.
   * @return slug
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A string that represents an organization. Specify either this or id. Cannot be used for accounts.")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public ContextOwner type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the owner. Defaults to \&quot;organization\&quot;. Accounts are only used as context owners in server.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of the owner. Defaults to \"organization\". Accounts are only used as context owners in server.")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextOwner contextOwner = (ContextOwner) o;
    return Objects.equals(this.id, contextOwner.id) &&
        Objects.equals(this.slug, contextOwner.slug) &&
        Objects.equals(this.type, contextOwner.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, slug, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextOwner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

