/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * InlineResponse2001Items
 */

public class InlineResponse2001Items {
  public static final String JSON_PROPERTY_VARIABLE = "variable";
  @JsonProperty(JSON_PROPERTY_VARIABLE)
  private String variable;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_CONTEXT_ID = "context_id";
  @JsonProperty(JSON_PROPERTY_CONTEXT_ID)
  private UUID contextId;

  public InlineResponse2001Items variable(String variable) {
    this.variable = variable;
    return this;
  }

   /**
   * The name of the environment variable
   * @return variable
  **/
  @ApiModelProperty(example = "POSTGRES_USER", required = true, value = "The name of the environment variable")
  public String getVariable() {
    return variable;
  }

  public void setVariable(String variable) {
    this.variable = variable;
  }

  public InlineResponse2001Items createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date and time the environment variable was created.
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "The date and time the environment variable was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public InlineResponse2001Items contextId(UUID contextId) {
    this.contextId = contextId;
    return this;
  }

   /**
   * ID of the context (UUID)
   * @return contextId
  **/
  @ApiModelProperty(required = true, value = "ID of the context (UUID)")
  public UUID getContextId() {
    return contextId;
  }

  public void setContextId(UUID contextId) {
    this.contextId = contextId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Items inlineResponse2001Items = (InlineResponse2001Items) o;
    return Objects.equals(this.variable, inlineResponse2001Items.variable) &&
        Objects.equals(this.createdAt, inlineResponse2001Items.createdAt) &&
        Objects.equals(this.contextId, inlineResponse2001Items.contextId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variable, createdAt, contextId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Items {\n");
    sb.append("    variable: ").append(toIndentedString(variable)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    contextId: ").append(toIndentedString(contextId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

