/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2006MostFailedTests
 */

public class InlineResponse2006MostFailedTests {
  public static final String JSON_PROPERTY_FAILED_RUNS = "failed_runs";
  @JsonProperty(JSON_PROPERTY_FAILED_RUNS)
  private Long failedRuns;

  public static final String JSON_PROPERTY_JOB_NAME = "job_name";
  @JsonProperty(JSON_PROPERTY_JOB_NAME)
  private String jobName;

  public static final String JSON_PROPERTY_P95_DURATION = "p95_duration";
  @JsonProperty(JSON_PROPERTY_P95_DURATION)
  private Double p95Duration;

  public static final String JSON_PROPERTY_TEST_NAME = "test_name";
  @JsonProperty(JSON_PROPERTY_TEST_NAME)
  private String testName;

  public static final String JSON_PROPERTY_TOTAL_RUNS = "total_runs";
  @JsonProperty(JSON_PROPERTY_TOTAL_RUNS)
  private Long totalRuns;

  public static final String JSON_PROPERTY_FLAKY = "flaky";
  @JsonProperty(JSON_PROPERTY_FLAKY)
  private Boolean flaky;

  public InlineResponse2006MostFailedTests failedRuns(Long failedRuns) {
    this.failedRuns = failedRuns;
    return this;
  }

   /**
   * The number of times the test failed
   * minimum: 0
   * @return failedRuns
  **/
  @ApiModelProperty(required = true, value = "The number of times the test failed")
  public Long getFailedRuns() {
    return failedRuns;
  }

  public void setFailedRuns(Long failedRuns) {
    this.failedRuns = failedRuns;
  }

  public InlineResponse2006MostFailedTests jobName(String jobName) {
    this.jobName = jobName;
    return this;
  }

   /**
   * The name of the job.
   * @return jobName
  **/
  @ApiModelProperty(required = true, value = "The name of the job.")
  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }

  public InlineResponse2006MostFailedTests p95Duration(Double p95Duration) {
    this.p95Duration = p95Duration;
    return this;
  }

   /**
   * The 95th percentile duration, in seconds, among a group of test runs.
   * @return p95Duration
  **/
  @ApiModelProperty(required = true, value = "The 95th percentile duration, in seconds, among a group of test runs.")
  public Double getP95Duration() {
    return p95Duration;
  }

  public void setP95Duration(Double p95Duration) {
    this.p95Duration = p95Duration;
  }

  public InlineResponse2006MostFailedTests testName(String testName) {
    this.testName = testName;
    return this;
  }

   /**
   * The name of the test.
   * @return testName
  **/
  @ApiModelProperty(required = true, value = "The name of the test.")
  public String getTestName() {
    return testName;
  }

  public void setTestName(String testName) {
    this.testName = testName;
  }

  public InlineResponse2006MostFailedTests totalRuns(Long totalRuns) {
    this.totalRuns = totalRuns;
    return this;
  }

   /**
   * The total number of times the test was run.
   * minimum: 0
   * @return totalRuns
  **/
  @ApiModelProperty(required = true, value = "The total number of times the test was run.")
  public Long getTotalRuns() {
    return totalRuns;
  }

  public void setTotalRuns(Long totalRuns) {
    this.totalRuns = totalRuns;
  }

  public InlineResponse2006MostFailedTests flaky(Boolean flaky) {
    this.flaky = flaky;
    return this;
  }

   /**
   * Whether the test is flaky.
   * @return flaky
  **/
  @ApiModelProperty(required = true, value = "Whether the test is flaky.")
  public Boolean getFlaky() {
    return flaky;
  }

  public void setFlaky(Boolean flaky) {
    this.flaky = flaky;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2006MostFailedTests inlineResponse2006MostFailedTests = (InlineResponse2006MostFailedTests) o;
    return Objects.equals(this.failedRuns, inlineResponse2006MostFailedTests.failedRuns) &&
        Objects.equals(this.jobName, inlineResponse2006MostFailedTests.jobName) &&
        Objects.equals(this.p95Duration, inlineResponse2006MostFailedTests.p95Duration) &&
        Objects.equals(this.testName, inlineResponse2006MostFailedTests.testName) &&
        Objects.equals(this.totalRuns, inlineResponse2006MostFailedTests.totalRuns) &&
        Objects.equals(this.flaky, inlineResponse2006MostFailedTests.flaky);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failedRuns, jobName, p95Duration, testName, totalRuns, flaky);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2006MostFailedTests {\n");
    sb.append("    failedRuns: ").append(toIndentedString(failedRuns)).append("\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    p95Duration: ").append(toIndentedString(p95Duration)).append("\n");
    sb.append("    testName: ").append(toIndentedString(testName)).append("\n");
    sb.append("    totalRuns: ").append(toIndentedString(totalRuns)).append("\n");
    sb.append("    flaky: ").append(toIndentedString(flaky)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

