/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The latest commit in the pipeline.
 */
@ApiModel(description = "The latest commit in the pipeline.")

public class PipelineListResponseVcsCommit {
  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  private String subject;

  public static final String JSON_PROPERTY_BODY = "body";
  @JsonProperty(JSON_PROPERTY_BODY)
  private String body;

  public PipelineListResponseVcsCommit subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * The subject of the commit message.
   * @return subject
  **/
  @ApiModelProperty(required = true, value = "The subject of the commit message.")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public PipelineListResponseVcsCommit body(String body) {
    this.body = body;
    return this;
  }

   /**
   * The body of the commit message.
   * @return body
  **/
  @ApiModelProperty(required = true, value = "The body of the commit message.")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PipelineListResponseVcsCommit pipelineListResponseVcsCommit = (PipelineListResponseVcsCommit) o;
    return Objects.equals(this.subject, pipelineListResponseVcsCommit.subject) &&
        Objects.equals(this.body, pipelineListResponseVcsCommit.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, body);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PipelineListResponseVcsCommit {\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

