version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - test
      - deploy:
          context: maven-central
          requires:
            - test
          filters:
            branches:
              only: master

jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    steps:
      - checkout
      - run: mvn -Drevision=2.0.${CIRCLE_BUILD_NUM} test -f ./v2/pom.xml
  deploy:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    steps:
      - checkout
      - run:
          name: Import GPG key
          command: echo -e "$GPG_SECRET_KEY" | gpg --import --batch
      - run: mvn -Drevision=2.0.${CIRCLE_BUILD_NUM} deploy -f ./v2/pom.xml -s ./settings.xml -P sign-artifacts