version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - test
      - deploy:
          context: maven-central
          requires:
            - test
          filters:
            branches:
              only: master

jobs:
  test:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    steps:
      - checkout
      - run: mvn test -f ./v2/pom.xml
  deploy:
    docker:
      - image: circleci/openjdk:11.0.4-stretch
    steps:
      - checkout
      - run: sed -ie "s/<version>1.0-SNAPSHOT<\/version>/<version>2.0.$CIRCLE_BUILD_NUM<\/version>/" ./v2/pom.xml
      - run: mvn deploy -f ./v2/pom.xml -s ./settings.xml