/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2001Items
 */
public class InlineResponse2001ItemsTest {
    private final InlineResponse2001Items model = new InlineResponse2001Items();

    /**
     * Model tests for InlineResponse2001Items
     */
    @Test
    public void testInlineResponse2001Items() {
        // TODO: test InlineResponse2001Items
    }

    /**
     * Test the property 'variable'
     */
    @Test
    public void variableTest() {
        // TODO: test variable
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

}
