/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject2
 */
public class InlineObject2Test {
    private final InlineObject2 model = new InlineObject2();

    /**
     * Model tests for InlineObject2
     */
    @Test
    public void testInlineObject2() {
        // TODO: test InlineObject2
    }

    /**
     * Test the property 'continuationKey'
     */
    @Test
    public void continuationKeyTest() {
        // TODO: test continuationKey
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

}
