/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.circleci.client.v2.model.InlineResponse2002MetricsDurationMetrics;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2002Metrics
 */
public class InlineResponse2002MetricsTest {
    private final InlineResponse2002Metrics model = new InlineResponse2002Metrics();

    /**
     * Model tests for InlineResponse2002Metrics
     */
    @Test
    public void testInlineResponse2002Metrics() {
        // TODO: test InlineResponse2002Metrics
    }

    /**
     * Test the property 'totalRuns'
     */
    @Test
    public void totalRunsTest() {
        // TODO: test totalRuns
    }

    /**
     * Test the property 'successfulRuns'
     */
    @Test
    public void successfulRunsTest() {
        // TODO: test successfulRuns
    }

    /**
     * Test the property 'mttr'
     */
    @Test
    public void mttrTest() {
        // TODO: test mttr
    }

    /**
     * Test the property 'totalCreditsUsed'
     */
    @Test
    public void totalCreditsUsedTest() {
        // TODO: test totalCreditsUsed
    }

    /**
     * Test the property 'failedRuns'
     */
    @Test
    public void failedRunsTest() {
        // TODO: test failedRuns
    }

    /**
     * Test the property 'successRate'
     */
    @Test
    public void successRateTest() {
        // TODO: test successRate
    }

    /**
     * Test the property 'durationMetrics'
     */
    @Test
    public void durationMetricsTest() {
        // TODO: test durationMetrics
    }

    /**
     * Test the property 'totalRecoveries'
     */
    @Test
    public void totalRecoveriesTest() {
        // TODO: test totalRecoveries
    }

    /**
     * Test the property 'throughput'
     */
    @Test
    public void throughputTest() {
        // TODO: test throughput
    }

}
