/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.circleci.client.v2.model.InlineResponse2006MostFailedTests;
import com.circleci.client.v2.model.InlineResponse2006TestRuns;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2006
 */
public class InlineResponse2006Test {
    private final InlineResponse2006 model = new InlineResponse2006();

    /**
     * Model tests for InlineResponse2006
     */
    @Test
    public void testInlineResponse2006() {
        // TODO: test InlineResponse2006
    }

    /**
     * Test the property 'averageTestCount'
     */
    @Test
    public void averageTestCountTest() {
        // TODO: test averageTestCount
    }

    /**
     * Test the property 'mostFailedTests'
     */
    @Test
    public void mostFailedTestsTest() {
        // TODO: test mostFailedTests
    }

    /**
     * Test the property 'mostFailedTestsExtra'
     */
    @Test
    public void mostFailedTestsExtraTest() {
        // TODO: test mostFailedTestsExtra
    }

    /**
     * Test the property 'slowestTests'
     */
    @Test
    public void slowestTestsTest() {
        // TODO: test slowestTests
    }

    /**
     * Test the property 'slowestTestsExtra'
     */
    @Test
    public void slowestTestsExtraTest() {
        // TODO: test slowestTestsExtra
    }

    /**
     * Test the property 'totalTestRuns'
     */
    @Test
    public void totalTestRunsTest() {
        // TODO: test totalTestRuns
    }

    /**
     * Test the property 'testRuns'
     */
    @Test
    public void testRunsTest() {
        // TODO: test testRuns
    }

}
