/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.circleci.client.v2.model.InlineResponse200MetricsDurationMetrics;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse200Metrics
 */
public class InlineResponse200MetricsTest {
    private final InlineResponse200Metrics model = new InlineResponse200Metrics();

    /**
     * Model tests for InlineResponse200Metrics
     */
    @Test
    public void testInlineResponse200Metrics() {
        // TODO: test InlineResponse200Metrics
    }

    /**
     * Test the property 'successRate'
     */
    @Test
    public void successRateTest() {
        // TODO: test successRate
    }

    /**
     * Test the property 'totalRuns'
     */
    @Test
    public void totalRunsTest() {
        // TODO: test totalRuns
    }

    /**
     * Test the property 'failedRuns'
     */
    @Test
    public void failedRunsTest() {
        // TODO: test failedRuns
    }

    /**
     * Test the property 'successfulRuns'
     */
    @Test
    public void successfulRunsTest() {
        // TODO: test successfulRuns
    }

    /**
     * Test the property 'throughput'
     */
    @Test
    public void throughputTest() {
        // TODO: test throughput
    }

    /**
     * Test the property 'mttr'
     */
    @Test
    public void mttrTest() {
        // TODO: test mttr
    }

    /**
     * Test the property 'totalCreditsUsed'
     */
    @Test
    public void totalCreditsUsedTest() {
        // TODO: test totalCreditsUsed
    }

    /**
     * Test the property 'durationMetrics'
     */
    @Test
    public void durationMetricsTest() {
        // TODO: test durationMetrics
    }

}
