/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2006MostFailedTests
 */
public class InlineResponse2006MostFailedTestsTest {
    private final InlineResponse2006MostFailedTests model = new InlineResponse2006MostFailedTests();

    /**
     * Model tests for InlineResponse2006MostFailedTests
     */
    @Test
    public void testInlineResponse2006MostFailedTests() {
        // TODO: test InlineResponse2006MostFailedTests
    }

    /**
     * Test the property 'failedRuns'
     */
    @Test
    public void failedRunsTest() {
        // TODO: test failedRuns
    }

    /**
     * Test the property 'jobName'
     */
    @Test
    public void jobNameTest() {
        // TODO: test jobName
    }

    /**
     * Test the property 'p95Duration'
     */
    @Test
    public void p95DurationTest() {
        // TODO: test p95Duration
    }

    /**
     * Test the property 'testName'
     */
    @Test
    public void testNameTest() {
        // TODO: test testName
    }

    /**
     * Test the property 'totalRuns'
     */
    @Test
    public void totalRunsTest() {
        // TODO: test totalRuns
    }

    /**
     * Test the property 'flaky'
     */
    @Test
    public void flakyTest() {
        // TODO: test flaky
    }

}
