/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2006TestCounts
 */
public class InlineResponse2006TestCountsTest {
    private final InlineResponse2006TestCounts model = new InlineResponse2006TestCounts();

    /**
     * Model tests for InlineResponse2006TestCounts
     */
    @Test
    public void testInlineResponse2006TestCounts() {
        // TODO: test InlineResponse2006TestCounts
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'failure'
     */
    @Test
    public void failureTest() {
        // TODO: test failure
    }

    /**
     * Test the property 'skipped'
     */
    @Test
    public void skippedTest() {
        // TODO: test skipped
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
