/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse200MetricsDurationMetrics
 */
public class InlineResponse200MetricsDurationMetricsTest {
    private final InlineResponse200MetricsDurationMetrics model = new InlineResponse200MetricsDurationMetrics();

    /**
     * Model tests for InlineResponse200MetricsDurationMetrics
     */
    @Test
    public void testInlineResponse200MetricsDurationMetrics() {
        // TODO: test InlineResponse200MetricsDurationMetrics
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'mean'
     */
    @Test
    public void meanTest() {
        // TODO: test mean
    }

    /**
     * Test the property 'median'
     */
    @Test
    public void medianTest() {
        // TODO: test median
    }

    /**
     * Test the property 'p95'
     */
    @Test
    public void p95Test() {
        // TODO: test p95
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'standardDeviation'
     */
    @Test
    public void standardDeviationTest() {
        // TODO: test standardDeviation
    }

}
