/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2004MetricsDurationMetrics
 */
public class InlineResponse2004MetricsDurationMetricsTest {
    private final InlineResponse2004MetricsDurationMetrics model = new InlineResponse2004MetricsDurationMetrics();

    /**
     * Model tests for InlineResponse2004MetricsDurationMetrics
     */
    @Test
    public void testInlineResponse2004MetricsDurationMetrics() {
        // TODO: test InlineResponse2004MetricsDurationMetrics
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'mean'
     */
    @Test
    public void meanTest() {
        // TODO: test mean
    }

    /**
     * Test the property 'median'
     */
    @Test
    public void medianTest() {
        // TODO: test median
    }

    /**
     * Test the property 'p95'
     */
    @Test
    public void p95Test() {
        // TODO: test p95
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'standardDeviation'
     */
    @Test
    public void standardDeviationTest() {
        // TODO: test standardDeviation
    }

}
