/*
 * CircleCI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JobDetailsExecutor
 */
public class JobDetailsExecutorTest {
    private final JobDetailsExecutor model = new JobDetailsExecutor();

    /**
     * Model tests for JobDetailsExecutor
     */
    @Test
    public void testJobDetailsExecutor() {
        // TODO: test JobDetailsExecutor
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'resourceClass'
     */
    @Test
    public void resourceClassTest() {
        // TODO: test resourceClass
    }

}
