/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PipelineConfig
 */
public class PipelineConfigTest {
    private final PipelineConfig model = new PipelineConfig();

    /**
     * Model tests for PipelineConfig
     */
    @Test
    public void testPipelineConfig() {
        // TODO: test PipelineConfig
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'compiled'
     */
    @Test
    public void compiledTest() {
        // TODO: test compiled
    }

    /**
     * Test the property 'setupConfig'
     */
    @Test
    public void setupConfigTest() {
        // TODO: test setupConfig
    }

    /**
     * Test the property 'compiledSetupConfig'
     */
    @Test
    public void compiledSetupConfigTest() {
        // TODO: test compiledSetupConfig
    }

}
