/*
 * CircleCI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PipelineWithWorkflowsWorkflows
 */
public class PipelineWithWorkflowsWorkflowsTest {
    private final PipelineWithWorkflowsWorkflows model = new PipelineWithWorkflowsWorkflows();

    /**
     * Model tests for PipelineWithWorkflowsWorkflows
     */
    @Test
    public void testPipelineWithWorkflowsWorkflows() {
        // TODO: test PipelineWithWorkflowsWorkflows
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
