/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.circleci.client.v2.model.PipelineListResponseVcsCommit;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PipelineListResponseVcs
 */
public class PipelineListResponseVcsTest {
    private final PipelineListResponseVcs model = new PipelineListResponseVcs();

    /**
     * Model tests for PipelineListResponseVcs
     */
    @Test
    public void testPipelineListResponseVcs() {
        // TODO: test PipelineListResponseVcs
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'originRepositoryUrl'
     */
    @Test
    public void originRepositoryUrlTest() {
        // TODO: test originRepositoryUrl
    }

    /**
     * Test the property 'targetRepositoryUrl'
     */
    @Test
    public void targetRepositoryUrlTest() {
        // TODO: test targetRepositoryUrl
    }

    /**
     * Test the property 'revision'
     */
    @Test
    public void revisionTest() {
        // TODO: test revision
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'commit'
     */
    @Test
    public void commitTest() {
        // TODO: test commit
    }

}
