/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.circleci.client.v2.model.PipelineListResponseTriggerActor;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PipelineListResponseTrigger
 */
public class PipelineListResponseTriggerTest {
    private final PipelineListResponseTrigger model = new PipelineListResponseTrigger();

    /**
     * Model tests for PipelineListResponseTrigger
     */
    @Test
    public void testPipelineListResponseTrigger() {
        // TODO: test PipelineListResponseTrigger
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'receivedAt'
     */
    @Test
    public void receivedAtTest() {
        // TODO: test receivedAt
    }

    /**
     * Test the property 'actor'
     */
    @Test
    public void actorTest() {
        // TODO: test actor
    }

}
