/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PipelineWithWorkflowsVcs
 */
public class PipelineWithWorkflowsVcsTest {
    private final PipelineWithWorkflowsVcs model = new PipelineWithWorkflowsVcs();

    /**
     * Model tests for PipelineWithWorkflowsVcs
     */
    @Test
    public void testPipelineWithWorkflowsVcs() {
        // TODO: test PipelineWithWorkflowsVcs
    }

    /**
     * Test the property 'providerName'
     */
    @Test
    public void providerNameTest() {
        // TODO: test providerName
    }

    /**
     * Test the property 'originRepositoryUrl'
     */
    @Test
    public void originRepositoryUrlTest() {
        // TODO: test originRepositoryUrl
    }

    /**
     * Test the property 'targetRepositoryUrl'
     */
    @Test
    public void targetRepositoryUrlTest() {
        // TODO: test targetRepositoryUrl
    }

    /**
     * Test the property 'revision'
     */
    @Test
    public void revisionTest() {
        // TODO: test revision
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

}
