/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectVcsInfo
 */
public class ProjectVcsInfoTest {
    private final ProjectVcsInfo model = new ProjectVcsInfo();

    /**
     * Model tests for ProjectVcsInfo
     */
    @Test
    public void testProjectVcsInfo() {
        // TODO: test ProjectVcsInfo
    }

    /**
     * Test the property 'vcsUrl'
     */
    @Test
    public void vcsUrlTest() {
        // TODO: test vcsUrl
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'defaultBranch'
     */
    @Test
    public void defaultBranchTest() {
        // TODO: test defaultBranch
    }

}
