/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md). API V1 [remains accessible here](https://circleci.com/docs/api/v1/)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RerunWorkflowParameters
 */
public class RerunWorkflowParametersTest {
    private final RerunWorkflowParameters model = new RerunWorkflowParameters();

    /**
     * Model tests for RerunWorkflowParameters
     */
    @Test
    public void testRerunWorkflowParameters() {
        // TODO: test RerunWorkflowParameters
    }

    /**
     * Test the property 'jobs'
     */
    @Test
    public void jobsTest() {
        // TODO: test jobs
    }

    /**
     * Test the property 'fromFailed'
     */
    @Test
    public void fromFailedTest() {
        // TODO: test fromFailed
    }

}
