/*
 * CircleCI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.circleci.client.v2.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Workflow
 */
public class WorkflowTest {
    private final Workflow model = new Workflow();

    /**
     * Model tests for Workflow
     */
    @Test
    public void testWorkflow() {
        // TODO: test Workflow
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'stoppedAt'
     */
    @Test
    public void stoppedAtTest() {
        // TODO: test stoppedAt
    }

    /**
     * Test the property 'pipelineId'
     */
    @Test
    public void pipelineIdTest() {
        // TODO: test pipelineId
    }

    /**
     * Test the property 'pipelineNumber'
     */
    @Test
    public void pipelineNumberTest() {
        // TODO: test pipelineNumber
    }

    /**
     * Test the property 'projectSlug'
     */
    @Test
    public void projectSlugTest() {
        // TODO: test projectSlug
    }

}
